#!/bin/sh

draft() {
    echo "Draft"
}

edit_draft() {
    echo "Edit Draft"
}

delete_draft() {
    echo "Delete Draft"
}

publish() {
    echo "Publish Draft"
}

edit_published() {
    echo "Edit Published"
}

delete_published() {
    echo "Delete Published"
}

main() {
    echo -e "Blog Management System\nEnter the characters contained in the brackets for the selected mode\n(d)raft a post\n(e)dit a (d)raft\n(d)elete a (d)raft\n(p)ublish a post\n(e)dit a (p)ubished post\n(d)elete a (p)ublished post"
    read -p "Selected Mode: " mode
    case "$mode" in
        "d") draft ;;
        "ed") edit_draft ;;
        "dd") delete_draft ;;
        "p") publish ;;
        "ep") edit_published ;;
        "dp") delete_published ;;
        *) echo "Invalid selection\n" && main ;;
    esac
}

main
